### ISSUE TITLE
Error: htmlCheckEncoding: unknown encoding gb2312

### ISSUE THREAD

**Issue by vincent-zheng** [rc0x03/node-osmosis#19]
# Problem:
When I crawl in the website which's url is http://news.163.com/15/0416/04/AN9VM4U600014AED.html. I get an unknown encoding error.
## Output:
 按照单位、�幸怠⑾钅俊⒌赜蛉哺堑谋曜迹婷�2013年
## Except Output:
按照单位、行业、项目、地域全覆盖的标准，全面摸清2013年

## Description:
 It use the gb2312 also call gbk for it's encoding, you can get the introduction of gb2312 in wikipedia(http://en.wikipedia.org/wiki/GB_2312). Before using the osmosis, I use the iconv-lite to solve the encoding error and I get the right answer at last, you  can refer to it.

## reference
https://github.com/ashtuchkin/iconv-lite
http://en.wikipedia.org/wiki/GB_2312

## ERROR:
   Error: htmlCheckEncoding: unknown encoding gb2312

**Comment by rc0x03** [comment]
The error is raised by `libxmljs` because it does not seem to include support that encoding. In an effort to keep Osmosis dependencies down to a minimum, `iconv-lite` isn't included by Osmosis to convert documents. Instead, Osmosis depends on `libxmljs` to do any character converting. Unfortunately, there is currently no plan to give Osmosis its own encoding support. A future release may include an option with a callback that will act as a document processing middleware after a request is made. This option would allow a callback function to convert the document encoding before sending it to `libxmljs` to parse. Until this option becomes available, the issue should be brought up at the [`libxmljs`](https://github.com/polotek/libxmljs) github page to see if `libxmljs` will add to its supported encodings.
