### ISSUE TITLE
How to get the HTML body string after the Osmosis followed some url?

### ISSUE THREAD

**Issue by zzyymaggie** [rc0x03/node-osmosis#20]
osmosis
.follow('a.result', function(context, data, nextPage) {
    // can I get the HTML body here?
})

**Comment by rc0x03** [comment]
If you mean just the context of the HTML `<body>`, then `context.get('body').toString()` should work. If you mean get the entire HTML document as a string, one solution would be to call `context.toString()`, however it's not the original string and could cause issues because it doesn't always perfectly serialize HTML (see: https://github.com/polotek/libxmljs/issues/213). The reason Osmosis doesn't retain the original HTML document string/buffer is to keep memory usage to a minimum. In a future release an option could be added that will cause Osmosis to store the original string in the `context` object.

**Comment by zzyymaggie** [comment]
💝

**Comment by rc0x03** [comment]
Support for this is coming in the next version. By setting the `keep_data` option to true, the original XML/HTML data is stored in `context.response.data`.

```javascript
osmosis
.config('keep_data', true)
.get('www.craigslist.org/about/sites')
.then(function(context, data, next) {
  console.log(context.response.data);
})
```

**Comment by rc0x03** [comment]
As of Osmosis 0.0.9 if `keep_data` is set to `true` then the response data will be stored in `context.response.data`, which is accessible from `.then()`.

**Comment by pingzh** [comment]
Looks like it should be:

```
osmosis.config('keep_data', true)

osmosis
.get('www.craigslist.org/about/sites')
.then(function(context, data, next) {
  console.log(context.response.data);
})
```
the version that I am using is 1.1.4
