### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by MMRandy** [rc0x03/node-osmosis#36]
What exactly is meant by "DOM support and the ability to run scripts/CSS without a headless browser"?

Does this mean that you will be able to scrape data from a page request that potentially uses AJAX calls or client side code to manipulate the DOM to be scraped?

**Comment by rc0x03** [comment]
Yes that is exactly what it will do. It will extend the libxmljs `Document` and `Element` types so that they have all the standard DOM properties and functions. For example `.dom` will call the provided function with the arguments `window`, `data`, and `next`. Where `window` and `window.document` etc. function just as they would in a browser.

A `.click` command and other interaction functions will be implemented soon. For example `.click("a[href^=javascript]")` will click all JS `<a>` elements and the resulting JavaScript will then be executed. If it causes the window to redirect, the newly loaded page will be passed down the command chain. If it causes AJAX content to be loaded and added to the DOM, then and `.find`s or `set`s, etc. will be able to access the new content.

Because osmosis is in control of every aspect of the DOM, the user will be able to closely control and monitor on-page events and HTTP requests.

In addition to JS/DOM support, basic CSS stylesheet  parsing will be provided. Osmosis will not interpret the CSS, just parse it and distribute the rules to the intended elements. That gives a user easy access to element styles like color and background image.
