### ISSUE TITLE
"done" in the command chain

### ISSUE THREAD

**Issue by anasqadrei** [rc0x03/node-osmosis#39]
Shouldn't done be called after all other commands are finished? If you run this example:
```
var fs = require('fs');
var osmosis = require('osmosis');

osmosis
.get('www.craigslist.org/about/sites')
.data(function(data) {
    //call an io function
    fs.readdir('.', function(err, files){
      console.log('data ... working on %s files', files.length);
    });
})
.then(function(context, data, next) {
    //call an io function
    fs.readdir('.', function(err, files){
      console.log('then ... working on %s files', files.length);
      next(context, data);
    });
})
.done(function(){
  console.log('done');
})
```
the result will be
```
done
data ... working on 18 files
then ... working on 18 files
```
Shouldn't "done" come last?

**Comment by rc0x03** [comment]
Yes, `done` should be called after all callbacks and commands have called "next(context, data)". The `data` callback function can operate after Osmosis is done parsing because `.data` doesn't expect a context or data object to pass back down.

The problem here is that `then` should come _before_ the `data` command. Alternatively, if you don't need the `context` object you could move your `then` code to the `data` callback. If you do need the context object, then you can move your `data` code to the `then` callback`.

The easiest way to fix this would be to just move your `.then` so that it`s right before `.data`. The order of the `console.log` messages will then be: `then`, `done`, then `data`. The reason `data` appears to happen last is because it's printing after an async function (`fs.readdir`) has been called. It only appears to be happening first because async calls happen on the next "tick". So `done` _is_ the last thing being called, which means Osmosis is done doing everything it needs to and now your callback code is doing what it needs to.

To verify this:
```javascript

var fs = require('fs');
var osmosis = require('osmosis');

osmosis
.get('www.craigslist.org/about/sites')
.data(function(data) {
    console.log('data');
})
.then(function(context, data, next) {
  console.log('then');
  next(context, data);
})
.done(function(){
  console.log('done');
})
```

**Comment by anasqadrei** [comment]
My real problem is something like this

```
osmosis
.get('www.craigslist.org/about/sites')
.then(function(context, data, next) {
  database.query(query, function(err, queryResults){
    //working on queryResults
    next(context, data);
  });
})
.done(function(){
  database.disconnect();
})
```
The problem is that it disconnects from the database before finishing the query which causes a database connection error in "then".

**Comment by rc0x03** [comment]
In that case, `done` shouldn't be called until `then` has called `next`. Obviously this must not be the case if you are still having an issue. Is your "working on queryResults" code asynchronous? this would cause `next` to be called before it finished working on the query.

**Comment by anasqadrei** [comment]
Yes `done` shouldn't be called until `then` has called `next`. But that is not the case.

This is another illustration that proves that `done` is not waiting for `next`. I'm setting a timeout of 5 seconds and then call `next`. 
```
var osmosis = require('osmosis');

osmosis
.get('www.google.com')
.then(function(context, data, next) {
    //call next after 5 secs
    setTimeout(function(){
      console.log('then');
      next(context, data);
    },5000);
})
.done(function(){
  console.log('done');
})
```
In that case, the output is `done` and 5 seconds later it writes `then`. Shouldn't `done` also wait 5 seconds for `next` to be called?

**Comment by rc0x03** [comment]
There seems to be an issue when using `then` immediately before `done`. If you place a command between `then` and `done` then the code works as expected. This should be fixed in the next release.

In my test code I used the `doc` command in between:
```javascript
var osmosis = require('/root/node-osmosis');

osmosis
.get('www.google.com')
.then(function(context, data, next) {
    //call next after 5 secs
    setTimeout(function(){
      console.log('then');
      next(context, data);
    },5000);
})
.doc()
.done(function(){
  console.log('done');
})
```

**Comment by rc0x03** [comment]
As of Osmosis version 0.0.9 significant stack counting changes were made and these issues should be resolved.
