### ISSUE TITLE
Is it possible to scrape binary data?

### ISSUE THREAD

**Issue by evandrix** [rc0x03/node-osmosis#7]
For instance:

```
osmosis
	.get("http://www.todayonline.com/print/1166611")
	.find("//*[@class='image-top']/img/@src")
	.set("img")
	.follow("@src")
...
```

Quite obviously, the call to `.follow("@src")` will return binary image data - which I can confirm is happening when I enable the log/debug/error hooks; I see 2 HTTP requests made, instead of 1, and also a whole bunch of XML parsing errors on the binary image data (to be expected).

I wonder if you've got any functionality to scrape the base64-encoded version of the raw image binary data, so that I can place it together with the its `@src` attribute, in the final `data` output?

**Comment by limtaesu** [comment]
you can download the image using the src that you got from scrapping,
then you can do anything that you need from it.

Scrapper should only scrape imo.

**Comment by rc0x03** [comment]
By default Osmosis expects HTML/XML and therefore will parse every HTTP request made. There is a `parse` option to tell Osmosis not to parse the response, however it's only intended to be used in `.then`. Using it outside of `.then` could cause issues. The reason multiple requests are being made is because  by default `tries` is set to 3 and if a parsing error occurs Osmosis will try to request the page again.

Here's what I'd do:
```javascript
osmosis
.get("http://www.todayonline.com/print/1166611")
.set("image", "//*[@class='image-top']/img/@src")
.then(function(img, data, next) {
    this.request('get', data['image'], null, function(err, response, buffer) {
        data['image_buf'] = buffer;
        next(img, data);
    })
})
```
Note: a callback with 3 arguments for `this.request` will automatically set the `parse` option to `false`. It's the same as:

```javascript
this.request('get', data['image'], null, function(err, response, buffer) {}, { parse: false})
```
